create table MEAL
(
    ID UUID PRIMARY KEY,
    ID_MEAL TEXT,
    NAME TEXT,
    CATEGORY TEXT,
    AREA TEXT,
    INSTRUCTIONS TEXT,
    IMAGE_LINK TEXT,
    YOUTUBE_LINK TEXT,
    TAGS TEXT,
    INGREDIENTS TEXT
);